import Head from "next/head";
import Link from "next/link";
import React from "react";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const {
    data,
    isFetching,
    isFetchingNextPage,
    isLoading,
    isError,
    hasNextPage, 
    fetchNextPage,
  } = api.example.infiniteProducts.useInfiniteQuery(
    {
        limit: 10
    },
    {
        getNextPageParam: (lastPage) =>  lastPage.nextCursor ,
        // initialCursor: 1,
    });

  const loadMoreProducts = async () => {
    try {
      const updatedProducts = await fetchNextPage()
      console.log("updatedProducts>>>", updatedProducts.data)
    } catch (error) {
      console.log("error>>>", error)
    }
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
          <div className="text-2xl text-white">
            {isFetching ? "Fetching tRPC query..." : null}
            {isFetchingNextPage ? "Fetching next page..." : null}
            {isLoading ? "Loading tRPC query..." : null}
            {isError ? "Error loading tRPC query" : null}
            {
              // bear with me, this is just to show the data
              data?.pages[data?.pages.length-1]?.products.map(
                (product) => <p key={product.id}>{ product.title }</p>
              )
            }
          </div>
          {hasNextPage ? <button className="text-2xl text-white" onClick={() => void loadMoreProducts()}>Load More</button> : null}
        </div>
      </main>
    </>
  );
}
